### ISSUE TITLE
find a way to fix gif bug

### ISSUE THREAD

**Issue by michellefilipaa** [DaanSchar/bamboogame#59]
tutorial gif only playing half of it

maybe we can have a timer that makes another screen pop up ontop of it with the second half (not great)
or we can try the video again

or just leave it idk

idea's are welcome

**Comment by FabianBB** [comment]
Isnt it playing the whole gif? Its just really fast and kinda hard to read

**Comment by michellefilipaa** [comment]
Does it end with “game over” ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FabianBB** [comment]
no :(
