### ISSUE TITLE
Add your algorithms here

### ISSUE THREAD

**Issue by DaanSchar** [DaanSchar/bamboogame#60]
Please comment with any articles that might be of any use here.
if it's a scientific paper, you get bonus points.

**Comment by Jolijn2020** [comment]
MiniMax search tree
https://reader.elsevier.com/reader/sd/pii/0004370283900012?token=240262B13AA9C06231813F69495335C040F496136184FD7D5C917CC8B8CEE335AA82E6FB26347FCEBC8A9A6937B35038&originRegion=eu-west-1&originCreation=20210924135715

**Comment by Jolijn2020** [comment]
although I realize that IF we wan to implement a multiplayer mode, miniMax might not work, since it was made for 2-player games. We would have to either adapt it or use another algorithm.

**Comment by michellefilipaa** [comment]
Supervised Learning ML algorithms in this 

https://www.ibm.com/cloud/learn/supervised-learning

tbh, I'm not too sure if I'm doing the right thing

**Comment by FabianBB** [comment]
I think this might be cool, but I cant access it. Do you know how to access ieee explore?

https://ieeexplore.ieee.org/abstract/document/6261563

**Comment by DaanSchar** [comment]
@FabianBB 
here is a link to the paper you're looking for:
https://sci-hub.se/10.1109/tsmcb.2012.2207951

**Comment by Jolijn2020** [comment]
reinforcement learning
http://incompleteideas.net/book/RLbook2020.pdf
chapter 1.5 gives a great explanation
