### ISSUE TITLE
replace TileMap by Hexagon

### ISSUE THREAD

**Issue by DaanSchar** [DaanSchar/bamboogame#63]
in logic, we have a a data structure class called Hexagon. the title of the issue is just a suggestion, but find some way of having all the frontend tiles be saved inside the Hexagon class. there is also an example inside Board.java for how to loop through this data structure. 
dont forget that they still need to be added to a pane to be rendered to the screen!

**Comment by DaanSchar** [comment]
if i'm being too vague just ask me anything

**Comment by FabianBB** [comment]
A few things, 
In TileMap where I also use 2d array, the upper left and lower right corner are the null values, which is exactly opposite of your comment in Hexagon.java, so should I change my implementation or change the comment.
Also I dont see any loops to fill the Hexagon?
And just in general im not sure what you want me to do, maybe ellaborate a bit further

**Comment by DaanSchar** [comment]
forget about the title of this issue, it's wrong. I've basiaclly moved your implementation of the TileMap into a class called Hexagon. inside Board.initBoard() you can see how we loop over this class to instantiate the tiles. 
Make it so that where we create the tilemap right now, we use a Hexagon class instead. this way we use the same class for the Logic as the frontend side.

**Comment by DaanSchar** [comment]
note: in the implementation of the class i mention that the bottom left and top right indices are null. with this i mean the first index and the last index, so array[0] (and some more if the hexagon is larger) and array[array.length-1]
