### ISSUE TITLE
Cleanup frontend code

### ISSUE THREAD

**Issue by DaanSchar** [DaanSchar/bamboogame#85]
this side of the code doesn't look too pretty, so it needs a bit of love.

- Delete stuff like unused methods and huge sections of commented code.
- Make the structure a bit more accessable and intuitive. (yes i know this is very vague)
- Segregate stuff into smaller methods. 
- Really think about when something needs to be public. if you dont need to access it from outside the class, make it private.
- Do we need a JavaFx class?

Try to find more stuff to clean up.

**Comment by michellefilipaa** [comment]
We don't need the JavaFX class.

Are you referring to the commented out lines and unused methods in the TileMap and Tile classes? 

I've changed the public variables to private now. 

I'm not sure how I'd "clean up" the MainMenu class without breaking it

**Comment by DaanSchar** [comment]
You can look for example the the HoverableButton class. it's a simple class but it's (imo) nicely structured. One thing you might notice here is the use of many small methods instead of few big methods. of course cleanliness is up to personal preference.

if you want to learn some basics about cleaning code, watch any of the lectures from Uncle Bob. watching one lecture should give you more than enough info about the ways.
